language: python
python:
    - "2.6"
    - "2.7"
    - "3.4"
install:
    - pip install coveralls
    - pip install tox
script:
    - tox
after_script:
    - mkdir -p build/logs
    - mv toxresults/* build/logs/
after_success:
    - coveralls
